/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BottomTab: typeof import('./components/BottomTab/index.vue')['default']
    copy: typeof import('./components/sign copy/index.vue')['default']
    HeaderSearch: typeof import('./components/HeaderSearch/index.vue')['default']
    I18n: typeof import('./components/i18n/index.vue')['default']
    Login: typeof import('./components/Login/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sign: typeof import('./components/Sign/index.vue')['default']
    SwitchLang: typeof import('./components/SwitchLang/index.vue')['default']
  }
}
